export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "#0f1930",
        "outline": "#6d758c",
        "on-error-container": "#ffa8a3",
        "on-secondary-fixed": "#40009b",
        "on-primary-container": "#00343e",
        "on-primary-fixed": "#003640",
        "background": "#060e20",
        "on-tertiary-fixed": "#00163b",
        "error-dim": "#d7383b",
        "on-background": "#dee5ff",
        "outline-variant": "#40485d",
        "tertiary-fixed-dim": "#74a2ff",
        "secondary-fixed-dim": "#ceb9ff",
        "primary-fixed-dim": "#40ceed",
        "surface-bright": "#1f2b49",
        "secondary-fixed": "#dac9ff",
        "on-secondary-fixed-variant": "#5f28c8",
        "on-surface-variant": "#a3aac4",
        "primary-dim": "#40ceed",
        "surface-container-highest": "#192540",
        "on-tertiary-container": "#00153a",
        "primary-fixed": "#53ddfc",
        "surface-variant": "#192540",
        "inverse-primary": "#00687b",
        "on-secondary-container": "#d9c8ff",
        "surface-container-low": "#091328",
        "error": "#ff716c",
        "on-tertiary": "#002355",
        "surface-dim": "#060e20",
        "secondary": "#ac8aff",
        "surface": "#060e20",
        "tertiary-fixed": "#8bb0ff",
        "primary": "#53ddfc",
        "on-secondary": "#280067",
        "surface-container-high": "#141f38",
        "tertiary-container": "#6294f6",
        "surface-tint": "#53ddfc",
        "tertiary-dim": "#6b9cfe",
        "tertiary": "#74a2ff",
        "surface-container-lowest": "#000000",
        "on-tertiary-fixed-variant": "#00367c",
        "secondary-container": "#5516be",
        "error-container": "#9f0519",
        "on-primary": "#004b58",
        "on-surface": "#dee5ff",
        "on-primary-fixed-variant": "#005564",
        "inverse-surface": "#faf8ff",
        "inverse-on-surface": "#4d556b",
        "secondary-dim": "#8455ef",
        "on-error": "#490006",
        "primary-container": "#21bedc"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
